@id=f3625fdc-dbd8-4c07-b15c-9d5fb6b3f1de

PUT http://localhost:5250/Registration/{{id}}
Content-Type: application/json

{
    "UserName": "Mahdi_Mohamadiha 2",
    "Password": "mahdi4321",
    "FirstName": "Mahdi",
    "LastName": "Mohamadiha",
    "City": "Qazvin",
    "PhoneNumber": "09109935732",
    "BirthDate": "2002-07-28"
}