@id=1072824b-da53-4795-8ba9-2ce2fa0719a2

PUT http://localhost:5250/Registration/{{id}}
Content-Type: application/json

{
    "UserName": "Mahdi_Mohamadiha",
    "Password": "mahdi4321",
    "FirstName": "Mahdi",
    "LastName": "Mohamadiha",
    "City": "Qazvin",
    "PhoneNumber": "09109935732",
    "BirthDate": "2002-07-28"
}